---
output: github_document
always_allow_html: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# APO-SUB-2: Investigating the origin of nutrients in closed freshwater aquaculture systems
It is assumed that the majority of nutrients enters an aquaculture system via the feed. However, when focussing on "downstream utilization" of nutrients, it must be considered that a fraction of the import flow of nutrients is being retained in the biomass before being available "for further use".



# TO DO

### Introduction
- update intro



### Methodology
- add sentence regarding MLE 
- improve explanation for alkalinity supps



# REVIEW

*italic:* already addressed

- *L125 typo DNA*
- consider mentioning HCO as macronutrient for plants (but are omitted in our study due to ....) 
- consider Si as "essential for plants in Chap3
- *Fig2 the N values are in some cases overlapping with the plots*
- *L191, I would say that the improvements of aquafeeds have higher effects than the protein sparing effect*
- *L192, decreased by 39%, not-39%*
- *Fig3 - try to make it bigger, some of the plots are not visible (such as plant with all the outliers)*
- *L260 Figure??*
- L262 will you then continue with the 19% N retention?; 
- *L302 per TAN excreted or per g of N input?*
- L329 - I would need en explanations... it seems too high...; 
- *L376 somehow complicated sentence*
- L381 - what if I use the denitrifictaion unit? in that case I can go as low as 10L.kg-1 of feed input - maybe I would make some not in the methodology that systems with denitrifictaion units are not taken into account as the N is lost in atmoshpere - not compatible with sustainability
- L388 maybe I would alsi pointed out that 1000 L. kg-1 feed is somehow extreme - something like flowtrough systems.; 


