---
title: "Unraveling the sources of nutrients and their contributions to the total input in aquaponic systems"
author:
  - name: Anıl Axel Tellbüscher
    email: atellbuscher@frov.jcu.cz
    affiliation: USB
    footnote: 1
  - name: Radek Gebauer
    email: rgebauer@frov.jcu.cz
    affiliation: USB
    footnote: 2
  - name: Jan Mráz
    email: jmraz@frov.jcu.cz
    affiliation: USB
    correspondingauthor: true
address:
  - code: USB
    organization: University of South Bohemia in České Budějovice, Faculty of Fisheries and Protection of Waters, South Bohemian Research Center of Aquaculture and Biodiversity of Hydrocenoses, Institute of Aquaculture and Protection of Waters
    addressline: Na Sádkach 1780
    city: 37005 České Budějovice
    country: Czech Republic
footnote:
  - code: 1
    text: "This is the first author footnote."
  - code: 2
    text: "Another author footnote."
abstract: |
  While input routes of nutrients into aquaculture and aquaponic systems are known, their contribution to the total nutrient input remains unclear.
keywords: 
  - tap water
  - minerals
  - fish feed
  - alkalinity supplements
journal: "Reviews in Aquaculture"
date: "`r Sys.Date()`"
classoption: preprint, 3p, authoryear
bibliography: ../references.bib
linenumbers: true
numbersections: true
# Use a CSL with `citation_package = "default"`
# csl: https://www.zotero.org/styles/elsevier-harvard
output: 
  rticles::elsevier_article:
    includes:
      in_header: ../latex/preamble.tex
    keep_tex: true
    citation_package: default
---

```{r message=FALSE, warning=FALSE, include=FALSE}
# Knitr options
knitr::opts_chunk$set(echo = FALSE)

options(digits = 1)

# Load packages
library(here)
library(XLConnect)
library(readxl)
library(tidyverse)
library(gdata)
library(viridis)
library(RColorBrewer)
library(bookdown)
library(png)
```

# Introduction
Nutrients enter aquaponic systems through the source water, alkalinity supplements used for pH control, and the daily ration of feed for the aquatic livestock, hereinafter denoted as aquafeed [@Rakocy2006; @Eck2019; @Robaina2019].

The importance of water as nutrient source is usually seen as negligible [@Schmautz2016]. However, it was found that it can introduce large amounts of some plant nutrients such as calcium (Ca), magnesium (Mg) and sulfur (S) [@Delaide2017]. Though, water can vary in its composition, depending on its origin. A glimpse of the extent of variability of terrestrial waters in their chemical composition is provided in Figure 1.1. Weathering of rock, ion exchange, redox reactions and the buildup of biomass are the main processes that are affecting concentrations of the shown compounds [@Stumm1981]. The highest variability can be found in anionic compounds such as nitrate (\ce{NO3-}) and sulfate (\ce{SO4^2-}) and the cationic alkaline earth metals \ce{Ca^2+} and \ce{Mg^2+} that are covering a concentration range of approximately two orders of magnitude.

The term alkalinity supplements summarizes several alkaline substances that are used to maintain a stable pH in the water [@Timmons2010]. Nitrification decreases the pH over time and, consequently, also the activity of nitrifyers [Ward2011]. Thus, a stable pH has to be maintained to ensure both high nitrification performance and animal welfare. For this purpose, several Na-based substances such as sodium hydrogen carbonate (baking soda, \ce{NaHCO3}) are commonly used in aquaculture due to their high and rapid solubility at a comparably cheap price. However, high sodium (Na) concentrations must be avoided in aquaponic systems due to its phytotoxicity [@Maathuis2014]. Na is therefore replaced with several other supplements based on K or Ca that come with the benefit of providing an additional source of nutrients besides increasing the pH.

Aquafeeds are considered to be the most important source of nutrients, providing a large and continuous nutrient input into the system. Formulating a specific aquaponics feed was thus thought to be the most suitable approach to develop an “off-the-shelf” nutrient delivery system [@Lennard2017; @Eck2019]. When discussing aquafeeds as nutrient input route, it is important to consider pathways of diet utilization, as shown in Figure 1.2. Uneaten feed and the indigestible mass fraction of ingested feed make up the solid wastes. The digestible mass fraction is meanwhile utilized to sustain the animals’ basal metabolism, somatic growth and reproductive activity. Metabolic end products are then excreted via the gills and the urinary system in form of dissolved matter [@Hardy2003; @Evans2005]. Only the dissolved fraction of the nutrients is immediately available for plant uptake via the root system.

The availability of digestibility, retentiton and excretion data for individual nutrients, with the former expressed with apparent digestibility coefficients (ADC), depends on whether the nutrient is essential and has to be considered for feed formulation. N that is, for the most part, present as crude protein (CP) in aquafeeds, is generally well-digestible, with ADCs usually being above \SI{70}{\p} and on average approximately \SI{90}{\p} [@Guillaume2001; @IAFFD2021]. The excretion of N as end product of the protein and amino acid catabolism takes place in form of ammonia (\ce{NH3}) and, to a small extent, urea. The predominant excretory site are the gills, followed by renal excretion [@Dabrowski2003]. A less digestible nutrient is P with ADC ranging from \SI{70}{\p} to only \SI{40}{\p} and a resulting excretion of \SI{30}{\p} to \SI{60}{\p} of the supply [@Lall2003; @Sugiura2018]. Especially plant ingredients in aquafeeds can cause low ADC if they are rich in phytic acid. Phytic acid is poorly digestible and can furthermore reduce the digestibility of minerals in the feed. This might also explain contradictory information in literature with reported renal excretion rates of \SI{90}{\p} of the total excreta [@Lall2003] in contrast to estimates of \SI{28}{\p} of excretion taking place in dissolved form and \SI{30}{\p} to \SI{64}{\p} excreted as particulate P [@Dabrowski2003]. Studies about ADCs of the remaining plant nutrients are scarce. Variability of ADC among different feed ingredients was shown in Atlantic salmon (\emph{Salmo salar}) for Ca, Mg, Fe, Mn and Zn, with ADCs ranging between \SIrange{30}{50}{\p} [@Sugiura1998]. Excretion of the earth alkaline metals Ca and Mg primarily occurs in dissolved form via the gills and urine [@Oikari1985; @Lall2003]. Mn, in contrast, is mostly excreted in solid form as feces, while renal excretion was found to be negligible [@Lall2003]. Cu is predominantly excreted via the bile [@Bury2003]. Excess dietary Cu is not taken up but excreted as feces. Cu inclusion rates in aquafeeds are thus reduced to minimize its release into the environment [@Lall2003]. Excretion of Zn mostly takes place renally and via the gills [@Lall2003]. Given the above-stated information, an animal nutritionist’s approach to develop a tailor-made aquafeed for aquaponics might follow the paradigm that a target concentration of nutrients, for instance given by commonly used hydroponic nutrient solutions in hydroponics such as Hoaglands solution [@Resh2016] is taken as template. Inclusion rates of the respective nutrients might eventually be back-calculated using nutrient digestibility and retention data. Within this context, it is necessary to ensure those nutrients can be supplied without facing the risk of over- or undersupply. Therefore, it is necessary to have profound knowledge about the variability of nutrient concentrations within their respective nutrient sources. Furthermore, it needs to be considered that physico-chemical constraints might limit the concentration of a substance in solution. Accordingly, previous studies found that the concentrations of some nutrients were not responsive to elevated inclusion rates in aquafeeds. It is thus worth to extend the nutritionist’s approach, illuminating the “aquaponic dark room” with respect to the chemical fate and behavior of nutrients.


## Objectives
This study reviews aquaponics studies in an attempt to exemplary identify the average contribution of different nutrient sources and their variability with respect to the total daily nutrient inputs. Recommendations with regards to the potential formulation of tailored aquafeeds and nutrient management in aquaponics shall eventually be developed to enhance the overall performance and profitability of aquaponic systems.





# Methodology

## Data acquisition and wrangling
Literature was screened for studies that focussed on nutrient dynamics in aquaponic systems, resulting in an initial dataset (IDS) of 117 individual observations originating from 39 publications. Selected literature comprised studies about permanently and on-demand coupled freshwater aquaponics, sludge remineralisation studies and hydroponic growth trials with water originating from aquaculture systems. The cultivated species, location of the experimental site, pH, volume of the system parts, daily water exchange rate, initial and final bodyweight, stocking density, daily feeding rate, feed name, and the concentrations of all essential plant nutrients in the source water, feed, and system water were collected.
The data acquisition and processing steps are graphically summarised in Figure 2.1. 


## Rearing assumptions

To calculate the proportion contribution of the source water, feed and alkalinity supplements to the total daily nutrient input in the reviewed studies, their average daily inputs per volume unit had to be calculated. For this purpose, statistics describing the average experimental system, system parameters and nutrient inputs were derived from the IDS and merged with external data sources in a four-stage process.
The first step comprised the generation of system assumptions. For this purpose, a filter was applied to the IDS, only including studies that made use of an aquaculture unit, reported the total system volume and the final bodyweight of the livestock at the end of the experiment. The resulting filtered dataset (FDS1) held 39 observations originating from 10 publications. FDS1 was used to calculate the average system volume ($V_{tot}$; \si{\cubicm}), average bodyweight ($\text{ABW}$; \si{\g}), average number of livestock ($\text{AN}$), average livestock density ($\text{AD}$; \si{\kg\per\cubicm}), and average water exchange rate ($\text{AWE}$; \si{\cubicm\per\d}). ABW was defined as the mean bodyweight during the duration of experiment and was calculated as the arithmetic mean of the initial and final bodyweight. For the calculation of AD, AN and AWE, NA values were removed. Eventually, the average biomass (ABM; kg) was computed by multiplication of ABW with AN and unit conversion or, if only AD was given, by multiplication of AD with $V_{tot}$. Vice versa, in case AD was not reported, it was calculated by dividing ABM by $V_{tot}$. The average daily water exchange volume by multiplication of $V_{tot}$ with AWE.
The second step was estimating the daily nutrient input via source water. For this purpose, gathered location information in the FDS was used to search for water analysis reports provided by the closest water treatment plant. Only official reports provided by local authorities and water utilities in the corresponding municipalities were used to ensure that analyses were conducted according to internationally accepted laboratory standards. Both literature data and collected water analysis reports originated from a total of 12 countries, with 39 literature studies and 37 analysis reports. The country distribution of the literature data compared with gathered water analysis reports is shown in Figure 2.2. It was not possible to obtain water analysis reports from Finland, Iran, Israel and The Netherlands. Thus, reports from Austria, France, Portugal and Turkey were included instead.

In water analysis, it is common practice to report the value of the detection limit instead of the measured value in case that the analyte concentration found was below the sensitivity of the instrument used for measurement (Deutsches Institut für Normung e.V. 2008). Figure 2.3 shows the proportion of data for all considered analytes in the water analysis reports that were found to be below the detection limit. Retaining the detection limits in the dataset leads to mean concentration estimates that are too high. Therefore, concentration data was recalculated using the \emph{cenmle()} function from the R package NADA by maximum likelihood estimation (MLE) [@Helsel2011]. This ensured that the estimates for nutrient concentrations in tap water were reliable. The output was eventually used to calculate the two-sided \SI{90}{\p} confidence interval for the arithmetic mean of the concentration of each nutrient to describe the concentration range that will be found in \SI{90}{\p} of all cases where tap water is used. Finally, multiplying the obtained concentrations with AWE yielded the upper and lower limits of the \SI{90}{\p} confidence interval of total daily individual plant nutrient inputs via source water.

In the third step, daily nutrient inputs via aquafeeds were estimated. The IDS was filtered for studies reporting the name of the commercial aquafeed used (if not selfmade), the CP inclusion rate and the feeding rate. From the resulting FDS2, the average feeding rate ($FR$; \si{\p}), CP inclusion rate (ACP) and the averages of all plant nutrients were calculated. Due to lacking nutrient composition data, supplier datasheets were used and amended by literature data in case of utilization of commercial aquafeeds. Incomplete observations with respect to experimental feeds were handled in the same way, merging data from multiple publications if the same feed was used. NA values were removed for the computation of averages. Eventually, the average daily feed input ($FI$; \si{\kg\per\d}) was calculated by multiplying ABM from the generated system assumptions with XXXXX. 
By multiplying $FI$ with the average plant nutrient inclusion rates in the aquafeeds, the uncorrected total daily input of individual plant nutrients via aquafeeds could be calculated. Obtained values were then corrected by multiplication with apparent digestibility coefficients (ADC), accounting for the digestibility of aquafeeds by fish. An ADC of \SI{90}{\p} was assumed for N whereas the ADC of all other nutrients was assumed to be \SI{50}{\p} [@Lall2002]. Finally, it was assumed that \SI{50}{\p} of the digestible fraction is retained while the remaining \SI{50}{\p} is excreted in dissolved form [@Halver2003]. The indigestible part of the feed is excreted as solid feces and was thus assumed not to participate in chemical reactions in solution. Lastly, an estimate for the daily input of alkalinity supplements was derived from $AFI$. First, the daily CP input was calculated by multiplying $AFI$ with the percentage of $CP$ on dry matter basis in the feed.


## Software
All calculations were conducted using R (v4.2.2) with RStudio (“Spotted Wakerobin” Release) as graphical user interface.





# Results




##	Water, feed, and alkalinity supplements
The average nutrient composition of both aquafeeds and source water and the lower and upper limits of the \SI{90}{\p} confidence interval for source water are shown in Table 3.1. Figure 3.2 provides an additional graphical presentation of the findings with emphasis on the variability of nutrient contributions by source water.
The highest daily nutrient inputs with respect to the macronutrients N and P in the reviewed studies likely originated from aquafeeds, being on average 99.2% and 99.3%, respectively. The overall amounts of these two nutrients contributed by source water are negligible. Aquafeeds can also be assumed being the main source of the micronutrients Fe, Mn, Cu, Zn, and Mo, with an average contribution of 96.2%, 97.2%, 79.8%, 93.9% and 76.3%, respectively. Among these nutrients, Cu and Mo showed the highest variability with respect to the contribution of source water between locations (Cu 90% CI: 8%, 29.7%; Mo 90% CI: 14.7%, 29.3%), with up to almost a third of the daily inputs possibly entering the system via the water. Meanwhile, source water likely had a comparably high contribution to Mg and S. With 76.5% for Mg (90% CI: 72.1%, 79.7%) and 68.8% for S (90% CI: 58.9%, 74.8%), an average delivery of more than half of the daily input was found. Also, a considerable contribution to daily B (63.1%; 90% CI: 48.5%, 48.5%) and Ni (56.2%; 90% CI: 33.3%, 67.4%) inputs probably originated from the source water.

Inputs of the remaining two nutrients, K and Ca, were found to be heavily depending on the alkalinity supplement used. In absence of the alkalinity supplement, aquafeeds were found to have the greatest impact on K with a contribution of 81.16%, while a higher proportion of Ca (69.62%; 90% CI: 65.51%, 72.86%) would enter the system on average via the water, compared with an average of30.38% of feed contribution. The difference is more pronounced with respect to Na: 82.25% (90% CI: 73.11%, 86.76%) of the total input was calculated to originate from water while only 17.75% were found to enter the system via daily feeding. However, the calculated quantities of alkalinity supplements necessary to maintain a constant pH were found to dominate each input scenario, resulting in a contribution of more than 80% of the total input of K, Ca, or Na in any case. Table 3.2 summarizes some supplements, their properties and prices. Using one of these substances would result in the supplement contributing 98.7%, 86.5% or 96.3% of the total K, Ca or Na input, respectively. Regarding the costs for alkalinity supplements, Na based substances are the cheapest, with prices of between 0.01 and 0.03 EUR d-1, followed by Ca based supplements ranging in the same price class. The most expensive supplements to be used are those based on K. These substances would cause costs between 0.10 and 0.14 EUR d-1, thus being on average 6 times more expensive than Ca or Na based substances.





# Discussion
The contribution of different nutrient sources to the total daily nutrient inputs into an aquaponic system were compared based on assumptions derived from literature.
It could overall be confirmed by the current input scenario that aquafeeds serve as major nutrient input route for N, P, K, Fe, Mn, Cu, Zn, and Mo after consideration of digestibility and nutrient retention by fish. These results confirm prior findings (Delaide et al. 2017). Considering variability among locations, it could furthermore be confirmed that Ca, Mg, S, B and Na originate from source water. However, the variability found in the case of Ca


does not reflect the usual concentration range of approximately two orders of magnitude found in terrestrial waters [@Stumm1981]. A study reviewing the Ca concentration in tap waters from the USA and Canada found a range from \SIrange{1}{135}{\mgL} [@Morr2006]. Considering that the obtained results were obtained making use of assumptions, these initial assumptions need to be discussed. The species distribution with strong emphasis on Tilapia (\emph{Oreochromis} spp.) and African catfish (\emph{Clarias gariepinus}) matches with survey results obtained in Europe [@Villarroel2016], even though approximately half of the studies included in the dataset were conducted in the USA. However, surveys conducted in the USA also revealed that the species mostly cultivated in aquaponic systems are Tilapia (Love et al. 2015, Pattillo et al. 2022). On the other hand, the average stocking density of 7.69 kg m-3 that was used for the nutrient contribution calculations can neither be considered representative for the intensive cultivation of Tilapia nor for African catfish. While densities between \SIrange{10}{50}{\kg\per\cubicm} are reported as acceptable for cultivation in RAS systems [@El-Sayed2019], densities of \SI{120}{\kg\per\cubicm} were reported to be tolerated by the latter species without any adverse effects on fish health [@Nieuwegiessen2009]. Even though salmonids such as Rainbow trout (\emph{Oncorhynchus mykiss}) are seldom reared in aquaponic systems, they can tolerate stocking densities up to \SI{137}{\kg\per\cubicm}. Though, normal stocking densities range between \SIrange{10}{20}{\kg\per\cubicm}. The assumptions are rather on the lower end for salmonids [@Pennell1996]. Common carp (\emph{Cyprinus carpio}) is irrelevant for aquaponic systems due to its low market price. Though, it was found that fish welfare can be guaranteed at a stocking density of around \SI{28}{\kg\per\cubicm}, which is $\approx 4$ times higher than the assumed density [@Ruane2002]. Consequently, it can be expected that the contribution of aquafeeds to the total daily nutrient input under intensive rearing conditions for the mentioned fish species is considerably higher than assumed in this study. Though, the presented nutrient contribution scenario might be representative for the cultivation of Pikeperch due to the comparably low stocking densities ($\approx$\SI{5}{\kg\per\cubicm}) recommended for its cultivation [@Kestemont2015]. The average FR of 2% is in line with recommendations for the husbandry of Tilapia, Channel catfish (Ictalurus punctatus) and Common carp [@Lovell2003]. Another aspect with respect to the contribution of feeds is that the feed composition is, in adaptation to the species to be reared, variable. For instance, crude protein inclusion rates in commercial aquafeeds for the mentioned species range from 32% for O. spp. [@Wilson2003; @El-Sayed2019] to \SI{50}{\p} for Pikeperch [@Geay2015]. Further variation in the nutrient composition is introduced by feed manufacturers due to changes in its raw material composition made because of fluctuations in feed ingredient availability and market prices. While changes in the mass concentrations of crucial nutrients such as the crude protein (CP) inclusion rate are acceptable only within tight limits, this might not be the case for other nutrients that are disregarded in the formulation process. Overall, data about the inclusion rates of nutrients relevant for plants in commercial aquafeeds can be considered scarce because these compounds are either not essential for aquatic animals or can be taken up from water via the gills in sufficient quantities. These nutrients are thus usually not considered during feed formulation (Lall 2003). However, a comprehensive review about the range of plant nutrient mass concentrations in commercial aquafeeds has not yet been conducted to the best of the authors knowledge. The mean water exchange rate of 3% can be considered at the lower end of commonly reported water exchange rates for RAS and within the range recommended for aquaponic systems (Timmons 2010). Using analysis reports from municipal water suppliers can be considered as valid approach with respect to the acquisition of nutrient concentration data in source water as it was found by a prior survey that educators, including research institutions, usually use tap water (Love et al. 2015). It could be further argued that, due to its low water demand, aquaponics is generally seen as food production system suitable for urban areas or arid regions (Kloas et al. 2015, Joyce et al. 2019). Establishing an aquaponic system in these regions comes with limited access to water sources such as well water or rivers and lakes. Rainwater, on the other hand, would require large storage capacities. Tap water is thus assumed to be the most important water source. Recalculation of nutrient concentrations as response to high proportions of censored data where only the limit of detection is reported is a rather uncommon approach. However, removing the affected observations would have resulted in a loss of a large proportion of data and, in addition, would have led to an average value that is higher than the estimates obtained by recalculation because the remaining data consisted only of concentration values that are high enough to be determined. A similar result would have arisen from using the reported detection limits for the calculation of nutrient concentration means. The results of the nutrient concentration recalculation via MLE procedure can thus be considered closer to the true concentration means than the outcome of the other mentioned approaches. The daily quantity of alkalinity supplements to be added might be overestimated. In biofilters, both nitrification and denitrification processes usually occur due to partially anoxic conditions, for instance within biofilms. Denitrification yields alkalinity (Timmons 2010). However, the contribution of alkalinity supplements will likely still exceed 50% of the total daily nutrient inputs. Furthermore, the calculations assumed that the supplements would have a purity of 100%. In practice a lower purity, corresponding to a food grade certification, can be expected.


## Implications for the formulation of tailored aquaponics feeds
The development of a dedicated aquaponics feed is seen as potentially user-friendly and rapid way of adding nutrients to the system, resulting in close-to optimum concentrations for the plants. However, the results of this study imply several limitations for feed formulation. 

Firstly, considering potential precipitation, target nutrients for an increased delivery could include N, K, Mg, S, B, and Zn. This suggestion is partly confirmed by prior empirical studies. One of those found K, Mg, and Zn to accumulate out of the mentioned nutrients, with additional accumulation of P, Mn and Zn (Seawright et al. 1998). Another study reported N, K, and Mg accumulation alongside P and Cu (Shaw et al. 2022). The focus on K and Mg can thus be considered “safe”, considering the generally high solubility of both compounds (Lide 2007) and reported deficiencies for both in aquaponics (Lunda et al. 2019). Natural feed ingredients rich in K are soy lecithin (13.0% K on dry matter basis), vinasse (3.6% K on dry matter basis) and some protein feedstuffs such as poultry by-product meal (3.5% K on dry matter basis) and hydrolyzed fish solubles (2.4%-2.9% K on dry matter basis). Mg can be introduced to aquafeeds mostly via the use of seaweed (3.9% Mg on dry matter basis) (International Aquaculture Feed Formulation Database (IAFFD) 2021). The drawback of the use of some of the above-stated feed ingredients is that the target nutrient is usually accompanied by comparably high amounts of Na. Even though this study shows that aquafeeds were not the main input route of Na in the reviewed literature, it is nevertheless reasonable to attempt to decrease Na inclusion rates during feed formulation because the initial assumptions leading to the nutrient input scenarios are not representative for commercial systems, as described above. This could be done for instance by replacement of feed ingredients with high Na inclusion rates such as fish meal originating from marine fish by other protein feedstuffs. Another possibility is given by using food-grade salts of the desired nutrients. However, considering the nutrient input via feed (1.1%) in comparison with that of alkalinity supplements containing K (98.7%) in this study, it depends on target concentrations and costs whether it is reasonable or not to increase the inclusion rate of K in a tailored aquafeed versus using the respective alkalinity supplements. Furthermore, it remains questionable whether it is more meaningful to include, for instance, salts into the feed or to add them directly into the system. Inclusion rates of nutrients that are confirmed to be affected by precipitation (Ca, Fe) are, in turn, recommended to be decreased in case the nutrient is not essential for the livestock and a change in feed formulation economically viable. Reducing the amount of precipitated nutrients increases the overall nutrient use efficiency. This also accounts for P, Mn, Cu, and Zn. No clear recommendation can be given in terms of inclusion rates in aquafeeds tailored for aquaponics. More research is needed to gain a better understanding of the behavior of these compounds under aquaculture and aquaponic conditions.



## Conclusion
Nutrient imbalances in aquaponics appear to be a result of chemical constraints rather than imbalanced nutrient inputs. Aquaponic systems differ from hydroponics in terms of pH and DOM concentrations. Understanding the chemistry of aquaponics is thus of major importance to improve nutrient cycling within the system. When trying to improve system performance via formulation of a tailored aquafeed, reducing inclusion rates of nutrients affected by precipitation (Ca, Fe) appears to be more meaningful than increasing inclusion rates of well-soluble nutrients (K, Mg). These can instead be supplied via alkalinity supplements.



# References {-}

