ER <- 3    # Daily water exchange rate (%/V/day)
SD <- 25  # Fish density (kg/m^3)
FR <- 2    # Daily feeding rate per biomass unit (%/kg/day)
rearingV <- 10   # Volume of the rearing compartment (m^3)
totalV <- 15   # Total volume of the aquaculture unit (m^3)